### ISSUE TITLE
Cannot restore full permission after a loop encoded with labels

### ISSUE THREAD

**Issue by fpoli** [viperproject/carbon#352] opened 2020-03-27 11:35 UTC
Carbon reports an error for the following program, while Silicon doesn't. I think that the program is correct.

```rust
field f: Bool

predicate P(self: Ref) {
  acc(self.f)
}

method test(x: Ref, undef: Bool)
{
  inhale acc(P(x))
  exhale acc(P(x), 1/10)
  goto loop_head
  
  // === loop_head ===
  label loop_head
  
  if (undef) {
    goto after_loop
  }
  goto loop_body
  
  // === loop_body ===
  label loop_body
  inhale acc(P(x), 1/10)
  exhale acc(P(x), 1/10)
  goto loop_head
  
  // === after_loop ===
  label after_loop
  inhale acc(P(x), 1/10)
  exhale acc(P(x))  // ERROR <<<<<<
}
```

**Comment by gauravpartha** [comment] 2020-05-05 09:41
Carbon does not support loops formed via gotos.
Also jumping out of loops is not consistent with Silicon (see #270).
Duplicate of  #182.

**Closed by gauravpartha** 2020-05-05 09:41 UTC
